    #!/bin/sh
    # create list with the first 7 lines of all scripts in markdown
    # author: @fabiantheblind
    # the headlines are formated to point to github raw files
    # TODO:  
    # make a interface to add raw links right now it points to a fixed location
    # should maybe be a python script
#touch overview.md
if [ -e "TOC.md" ]; then
    echo "\"TOC.md\" already exists. I will remove it"
    rm TOC.md
fi
numfiles=(*)
numfiles=${#numfiles[@]}
echo "There are $numfiles .jsx / .txt / .sh files in this directory"
#echo ls -l | grep -c "^-.*"
echo "##Autogenerated TOC  " >> TOC.md;
for file in *.{jsx,json,txt,sh}; do
    if [ -e "$file" ]; then
        echo "###[${file}](https://raw.github.com/fabiantheblind/auto-typo-adbe-id/master/fabiantheblind/${file})  " >> TOC.md;
        #echo  "  \n" >> TOC.md;
        head -7 "${file}" >> TOC.md;
        #echo  "  \n" >> TOC.md;
        echo "  \\n--------------  \\n  " >> TOC.md;
    fi
done
open TOC.md
